### ISSUE TITLE
Getting error while caching

### ISSUE THREAD

**Issue by technicalbirdVayuz** [PythonicCafe/dokku-prerender#2]
<img width="971" alt="Screenshot 2024-02-29 at 11 41 00 AM" src="https://github.com/PythonicCafe/dokku-prerender/assets/18699624/c799836f-3d49-4286-b7c1-303a82e096ce">

**Comment by turicas** [comment]
Probably the permissions of `/var/lib/dokku/data/storage/<app_name>` are wrong. Did you run the `dokku storage:ensure-directory --chwon heroku $APP_NAME` command before the `storage:mount` as in README?
You can try to force the permissions (so the user inside the container will be able to write on it) by running on the host machine:
```shell
chown -R 1000:1000 /var/lib/dokku/data/storage/<app_name>
```

**Comment by technicalbirdVayuz** [comment]
Using docker on production directly, if I get inside the docker running container and go to the given path

Following path is not there, /var/lib/dokku/data/storage/<app_name>

<img width="1440" alt="Screenshot 2024-03-01 at 10 50 59 AM" src="https://github.com/PythonicCafe/dokku-prerender/assets/18699624/a924b13e-b96f-4796-bdb8-3ecc59619171">

Also, I have not given $APP_NAME anywhere

**Comment by turicas** [comment]
You don't have `$APP_NAME` because you did not follow the instructions on README, which is focused on running prerender on Dokku, not on Docker (the `compose.yml` is just to make local development easier).
To make this work you may need to change the volume permissions.
PLEASE send all the information so I can help you - [learn how to ask questions](https://www.freecodecamp.org/news/how-to-ask-good-technical-questions/) (give context, paste the command - not the screenshot, paste error messages, list everything you've tried etc.). If you can't provide it I'll just close the issue.

**Comment by technicalbirdVayuz** [comment]
Will it be possible for you to create ReadMe for docker also, this will solve the purpose

**Comment by turicas** [comment]
> Will it be possible for you to create ReadMe for docker also, this will solve the purpose

To run via compose you may need to change the ownership of the directory `${PWD}/cache`. The `Dockerfile` uses user `node` which has UID 1000, so you must force this UID on your machine also. To force it, run on the root of the repository:

```shell
sudo mkdir -p cache
sudo chown -R 1000:1000 cache
```

I'm going to force this on the `Makefile` `start` command and close this issue.

**Comment by technicalbirdVayuz** [comment]
This is working, thanks!

but while retrieving from cache there is an issue, Can you check that?

Also, not able to check the website on Google Page insights for performance, not able to perform live test once a URL is cached in Google search console

<img width="1040" alt="Screenshot 2024-03-20 at 12 54 11 PM" src="https://github.com/PythonicCafe/dokku-prerender/assets/18699624/329c5f47-f4ea-4b8d-ad21-3f299bf82e69">
